site_name: DIY Arcade Cabinet Project
site_url: https://your-github-username.github.io/project-name
repo_url: https://github.com/your-github-username/project-name
repo_name: your-github-username/project-name

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js

nav:
  - Home: index.md
  - Getting Started:
    - Project Overview: getting-started/overview.md
    - What You'll Need: getting-started/prerequisites.md
    - Choose Your Path: getting-started/deployment-options.md
  - Setting Up Accounts:
    - AWS Account: accounts/aws-setup.md
    - Stripe Account: accounts/stripe-setup.md
    - EMQX Account: accounts/emqx-setup.md
    - GitHub Setup (optional): accounts/github-setup.md
  - Quick Deploy Path:
    - Overview: quick-deploy/overview.md
    - Pull Docker Image: quick-deploy/docker-pull.md
    - AWS Configuration: quick-deploy/aws-config.md
    - Testing Your Setup: quick-deploy/testing.md
  - Custom Build Path:
    - Overview: custom-build/overview.md
    - Understanding the Code: custom-build/code-overview.md
    - Making Changes: custom-build/modifications.md
    - Building & Deploying: custom-build/deployment.md
  - How It Works:
    - System Architecture: how-it-works/architecture.md
    - Payment Flow: how-it-works/payment-flow.md
    - Game Control: how-it-works/game-control.md
    - Cloud Services: how-it-works/cloud-services.md
  - Tutorials:
    - Basic Setup: tutorials/basic-setup.md
    - Payment Integration: tutorials/payment-integration.md
    - Game Integration: tutorials/game-integration.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Getting Help: troubleshooting/getting-help.md
  - Reference:
    - API Documentation: reference/api-docs.md
    - Configuration Options: reference/config-options.md
    - Glossary: reference/glossary.md