site_name: DIY Arcade Cabinet Payment Integration Project
site_url: https://thunder-software-technology-malaysia.github.io/arcade-stem/
repo_url: https://github.com/Thunder-Software-Technology-Malaysia/arcade-stem
repo_name: Thunder-Software-Technology-Malaysia/arcade-stem

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js

nav:
  - Home: index.md
  - Getting Started:
    - Project Overview: getting-started/overview.md
    - What You'll Need: getting-started/prerequisites.md
    - Choose Your Path: getting-started/deployment-options.md
  - Setting Up Accounts:
    - AWS Setup: accounts/aws/basic-setup.md
    - Container Registry: accounts/aws/container-registry.md
    - EMQX Setup: accounts/emqx-setup.md
    - Stripe:
      - Basic Setup: accounts/stripe/stripe-setup.md
      - Creating Webhooks: accounts/stripe/stripe-webhooks.md
    - GitHub Setup (optional): accounts/github-setup.md
  - Quick Deploy:
    - Overview: quick-deploy/overview.md
    - Pull Docker Image: quick-deploy/docker-pull.md
    - Setting Up AWS Lambda: quick-deploy/aws-lambda/quick-deploy-lambda-setup.md
    - Understanding API Gateway: quick-deploy/aws-lambda/api-gateway-intro.md
    - Configure API Gateway: quick-deploy/aws-lambda/setup-gateway.md
    - Test Your Deployment: quick-deploy/aws-lambda/test-deployment.md
    - Final Testing: quick-deploy/testing.md
  - Custom Build:
    - Overview: custom-build/overview.md
    - Code Overview: custom-build/code-overview.md
    - Build and Test: custom-build/build-and-test.md
    - First Deployment: custom-build/first-deployment.md
    - Setting Up AWS Lambda: custom-build/aws-lambda/lambda-setup.md
    - Understanding API Gateway: custom-build/aws-lambda/api-gateway-intro.md
    - Configure API Gateway: custom-build/aws-lambda/setup-gateway.md
    - Test Your Deployment: custom-build/aws-lambda/test-deployment.md
    - Making Modifications: custom-build/modifications.md
    - Deploying Changes: custom-build/deploying-changes.md
  - How It Works:
    - Architecture: how-it-works/architecture.md
    - Payment Flow: how-it-works/payment-flow.md
    - Game Control: how-it-works/game-control.md
    - Cloud Services: how-it-works/cloud-services.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Getting Help: troubleshooting/getting-help.md
  - Reference:
    - API Documentation: reference/api-docs.md
    - Configuration Options: reference/config-options.md
    - Glossary: reference/glossary.md
